# Generated by Django 3.1.5 on 2023-03-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('tel_number', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=8)),
                ('floor', models.CharField(max_length=10)),
                ('occupancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_guests', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('check_in', models.DateTimeField(verbose_name='check-in')),
                ('check_out', models.DateTimeField(verbose_name='check-out')),
                ('main_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.guest')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.room')),
            ],
        ),
    ]
