# Generated by Django 3.1.5 on 2023-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitems',
            options={'verbose_name_plural': 'Shop items'},
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('SNGL', 'Single'), ('DBL', 'Double'), ('TWN', 'Twin'), ('TRPL', 'Triple'), ('QUAD', 'Quad'), ('FML', 'Family')], max_length=8),
        ),
    ]
