# Generated by Django 4.1.7 on 2023-03-09 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 9, 24, 45, 942201, tzinfo=datetime.timezone.utc), verbose_name='check-out'),
        ),
    ]
