# Generated by Django 4.1.7 on 2023-03-09 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 13, 54, 29, 388011, tzinfo=datetime.timezone.utc), verbose_name='check-out'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
