# Generated by Django 3.1.5 on 2023-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CSH', 'Cash'), ('VCC', 'Visa(CC)'), ('MCC', 'Mastercard(CC)'), ('AMEX', 'American Express'), ('DC', 'Debit Card')], default=None, max_length=10),
        ),
    ]
