# Generated by Django 3.1.5 on 2023-03-16 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20230315_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 17, 13, 18, 43, 637336, tzinfo=utc), verbose_name='check-out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.room'),
        ),
    ]
