# Generated by Django 3.1.5 on 2023-03-16 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20230316_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 17, 15, 48, 22, 492793, tzinfo=utc), verbose_name='check-out'),
        ),
    ]
